name: Package Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup thrift
        uses: dodopizza/setup-thrift@v1
        with:
          version: 0.13.0
      - name: Generate code
        run: |
          thrift -r -gen java gensrc/StarrocksExternalService.thrift
          mkdir src/main/java/com/starrocks/connector/flink/thrift
          cp -r gensrc/gen-java/com/starrocks/connector/flink/thrift/* src/main/java/com/starrocks/connector/flink/thrift
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pacakge Test
        uses: xlui/action-maven-cli@jdk8
        with:
          lifecycle: 'clean validate package'
