name: Package Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pacakge Test
        uses: xlui/action-maven-cli@jdk8
        with:
          lifecycle: 'clean validate package'
